### ISSUE TITLE
Crashes instantly

### ISSUE THREAD

**Issue by ThomasDebrunner** [detlevn/QGIS-ConcaveHull-Plugin#5]
I tried to use the plugin, however as soon as I create a new Hull, the plugin crashes immediately with:

Traceback (most recent call last):
              File "~/.qgis2/python/plugins/concavehull/concavehull.py", line 709, in run
                geom.extend(extract_points(feat.geometry()))
              File "~/.qgis2/python/plugins/concavehull/concavehull.py", line 329, in extract_points
                if geom.type() == 0:
            AttributeError: 'NoneType' object has no attribute 'type'

Is my data malformatted or what could be the problem?

**Comment by detlevn** [comment]
Hi najiji, 
it seems that `feat.geometry()` returns `None` instead of some geometry. What geometry types are you processing? Can it happen, that some objects have invalid or no geometry?
If this is true than it would be a good idea to use a try/except block around these statements, so the process can skip this feature and proceed with the next one. I will change this for the coming version.
